{% set name = "fast-depends" %}
{% set version = "2.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fast_depends-{{ version }}.tar.gz
  sha256: 724a5068c3f955e02121a953428349ef34c8a2fadd65f073e94c94d54cec4554

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0
    - anyio >=3.0.0,<5.0.0

test:
  imports:
    - fast_depends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lancetnik/FastDepends
  summary: FastDepends - extracted and cleared from HTTP domain logic FastAPI Dependency Injection System. Async and sync are both supported.
  dev_url: https://github.com/Lancetnik/FastDepends
  doc_url: https://lancetnik.github.io/FastDepends/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
