{% set name = "fast-depends" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast_depends-{{ version }}.tar.gz
  sha256: c915a54d6e0d0f0393686d37c14d54d9ec7c43d7b9def3f3fc4f7b4d52f67f2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.2
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0
    - anyio >=4.0.0,<5.0.0
    - msgspec

test:
  imports:
    - fast_depends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Lancetnik/FastDepends
  summary: FastDepends - extracted and cleared from HTTP domain logic FastAPI Dependency Injection System. Async and sync are both supported.
  dev_url: https://github.com/Lancetnik/FastDepends
  doc_url: https://lancetnik.github.io/FastDepends/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
